// Generated by CoffeeScript 1.6.3
(function() {
  var MONGO_URI, app, db, express, port;

  express = require('express');

  app = express();

  port = process.env.PORT || 5000;

  app.listen(port, function() {
    return console.log("now listening on port " + port);
  });

  MONGO_URI = process.env.MONGOLAB_URI || process.env.MONGOHQ_URL || "builder";

  db = require("mongojs").connect(MONGO_URI, ['classes', 'sections', 'layouts', 'generics']);

  app.configure(function() {
    app.use(express.logger("dev"));
    app.set("views", __dirname + "/views");
    app.set("view engine", "jade");
    app.use(express.errorHandler());
    app.locals.pretty = true;
    app.use(express.cookieParser());
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    return app.use(express["static"](__dirname + "/public"));
  });

  app.get("/", function(req, res) {
    return res.render("index");
  });

  app.use(function(req, res) {
    return res.render("404");
  });

}).call(this);
